"""empty message

Revision ID: 28d3c2a5e2f3
Revises: 7a1e6eaf2c8d
Create Date: 2026-04-22 13:23:48.872012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '28d3c2a5e2f3'
down_revision: Union[str, Sequence[str], None] = '7a1e6eaf2c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_final', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detalles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria')
    # ### end Alembic commands ###
