"""empty message

Revision ID: ff0cb4fc5cc1
Revises: 28d3c2a5e2f3
Create Date: 2026-04-22 17:27:37.423185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ff0cb4fc5cc1'
down_revision: Union[str, Sequence[str], None] = '28d3c2a5e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuariodb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuariodb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuariodb_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuariodb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuariodb_email'))

    op.drop_table('usuariodb')
    # ### end Alembic commands ###
